"""Native (LLM-free) apply handlers for specific ATS platforms.

Each handler is a module in this package exposing `matches(url) -> bool`
and `apply(page, job, profile, dry_run) -> str | None`. Modules are
auto-discovered -- dropping a new file in here (by hand, or generated by
`applypilot.apply.sitegen`) is enough to register it, no edits needed here.

A handler's `apply()` returns None instead of a RESULT status whenever the
posting doesn't match what it knows how to do; the caller then falls back
to the full LLM agent so nothing is ever silently mishandled.
"""

import importlib
import logging
import pkgutil

logger = logging.getLogger(__name__)


def _discover_handlers() -> list:
    handlers = []
    for info in pkgutil.iter_modules(__path__):
        if info.name.startswith("_"):
            continue
        try:
            mod = importlib.import_module(f"{__name__}.{info.name}")
        except Exception:
            logger.exception("Failed to import site handler module '%s'", info.name)
            continue
        if callable(getattr(mod, "matches", None)) and callable(getattr(mod, "apply", None)):
            handlers.append(mod)
    return handlers


_HANDLERS = _discover_handlers()


def find_handler(url: str | None):
    """Return the handler module that owns this URL, or None."""
    if not url:
        return None
    for handler in _HANDLERS:
        try:
            if handler.matches(url):
                return handler
        except Exception:
            logger.exception("Handler '%s'.matches() crashed on %s", handler.__name__, url)
    return None


def reload_handlers() -> None:
    """Re-scan the package for handler modules (e.g. after generating a new one)."""
    global _HANDLERS
    _HANDLERS = _discover_handlers()
